### ISSUE TITLE
Updated Alpine Support

### ISSUE THREAD

**Issue by tbplayer7** [VividCortex/docker#23]
The image used in the base default docker image is alpine 3.8 which is officially [EOL](https://github.com/docker-library/official-images/pull/8089).  

I tried to PR a change to 3.12, and didn't have access.   I am testing this version of alpine in a current environment.  Feel free to reach out to me, and I can give you the details if you want to pull logs from this instance and agent to determine viability.

**Comment by AndyS-vc** [comment]
Hi folks - sorry this sat here mouldering quietly; we use artifacts repo for ticket flow, and no-one checks individual repos for issues. Think the usual route is to raise this to your CSE.

That said, @dominique-flannery brought this up, and I opened a ticket to backend.

**Comment by efepapa** [comment]
Closed via https://github.com/VividCortex/docker/pull/28 (Alpine 1.13.1)
